name: Latest Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
    - uses: actions/checkout@v2
      run: make

    - name: Push to Docker Hub
      if: github.event_name != 'pull_request'
    - run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        make push
